version: "3.8"
services:
  nginx:
    image: 215680092654.dkr.ecr.ap-south-1.amazonaws.com/nginx-server
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    image: 215680092654.dkr.ecr.ap-south-1.amazonaws.com/node-server
    build:
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/dev.env
    ports:
      - "5000:5000"
  client:
    image: 215680092654.dkr.ecr.ap-south-1.amazonaws.com/react-app
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
